
-- USER TABLE
CREATE TABLE USER (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

-- USER_PHONE TABLE (Multivalued Attribute)
CREATE TABLE USER_PHONE (
    UserID INT NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL UNIQUE,
    PRIMARY KEY (UserID, PhoneNumber),
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

-- ADMIN TABLE (Specialization)
CREATE TABLE ADMIN (
    UserID INT PRIMARY KEY,
    AccessScope VARCHAR(100) NOT NULL,
    FOREIGN KEY (Use
    rID) REFERENCES USER(UserID)
        ON DELETE CASCADE
);

-- DEALER TABLE (Specialization)
CREATE TABLE DEALER (
    UserID INT PRIMARY KEY,
    ShowroomName VARCHAR(150) NOT NULL,
    Location VARCHAR(150) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
        ON DELETE CASCADE
);

-- CUSTOMER TABLE (Specialization)
CREATE TABLE CUSTOMER (
    UserID INT PRIMARY KEY,
    Street VARCHAR(150) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Pincode VARCHAR(10) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
        ON DELETE CASCADE
);

-- CARMODEL TABLE
CREATE TABLE CARMODEL (
    ModelID INT PRIMARY KEY AUTO_INCREMENT,
    Brand VARCHAR(100) NOT NULL,
    ModelName VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    FuelType VARCHAR(50) NOT NULL,
    BasePrice DECIMAL(10,2) NOT NULL
);

-- CARINSTANCE TABLE
CREATE TABLE CARINSTANCE (
    CarID INT PRIMARY KEY AUTO_INCREMENT,
    VIN VARCHAR(50) NOT NULL UNIQUE,
    Status VARCHAR(50) NOT NULL,
    ModelID INT NOT NULL,
    DealerID INT NOT NULL,
    FOREIGN KEY (ModelID) REFERENCES CARMODEL(ModelID)
        ON DELETE CASCADE,
    FOREIGN KEY (DealerID) REFERENCES DEALER(UserID)
        ON DELETE CASCADE
);

-- PURCHASE TABLE
CREATE TABLE PURCHASE (
    PurchaseID INT PRIMARY KEY AUTO_INCREMENT,
    PurchaseDate DATE NOT NULL,
    FinalPrice DECIMAL(10,2) NOT NULL,
    CarID INT NOT NULL UNIQUE,
    CustomerID INT NOT NULL,
    FOREIGN KEY (CarID) REFERENCES CARINSTANCE(CarID)
        ON DELETE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(UserID)
        ON DELETE CASCADE
);

CREATE TABLE BOOKING (
    BookingID INT NOT NULL AUTO_INCREMENT,
    CustomerID INT DEFAULT NULL,
    ModelID INT DEFAULT NULL,
    DealerID INT DEFAULT NULL,
    Status VARCHAR(20) DEFAULT 'Unavailable',
    PRIMARY KEY (BookingID),
    
    CONSTRAINT booking_ibfk_1 FOREIGN KEY (CustomerID) REFERENCES USER(UserID),
    CONSTRAINT booking_ibfk_2 FOREIGN KEY (ModelID) REFERENCES CARMODEL(ModelID),
    CONSTRAINT booking_ibfk_3 FOREIGN KEY (DealerID) REFERENCES DEALER(UserID)
) 